### ISSUE TITLE
License for repository

### ISSUE THREAD

**Issue by tsalo** [mkassinopoulos/Noise_modeling_based_on_PPG#1]
The CPM looks very interesting and I'd love to try translating it to Python and incorporate it into a package like `phys2denoise`, but there is no license. Would you mind uploading an open source license dictating code reuse restrictions and the like?

**Comment by mkassinopoulos** [comment]
Thank you Taylor for pointing this out. I have just applied the Apache 2.0 license. Please don't hesitate to contact me if you need any help with the scripts.
